version: '3.7'
services:
  nginx:
    image: sajith75/nginx:latest
    ports:
    - target: 80
      published: 80
    depends_on:
    - api
    - react
  react:
    build: .
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=${PASS}
    - MYSQL_DATABASE=todo
  api:
    image: springapp
    depends_on:
    - db
